project_name: helmify
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/helmify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archives:
  -
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
brews:
  -
    tap:
      owner: onelapahead
      name: homebrew-tap
    commit_author:
      name: onelapahead
      email: torubarov-a-a@yandex.ru
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/onelapahead/helmify"
    description: "Creates Helm chart from Kubernetes yaml."
    license: "MIT"
    test: |
      system "#{bin}/helmify --version"
    install: |
      bin.install "helmify"
release:
  github:
    owner: onelapahead
    name: helmify